apiVersion: apps/v1
kind: Deployment
metadata:
  name: autohealing-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autohealing-app
  template:
    metadata:
      labels:
        app: autohealing-app
    spec:
      containers:
        - name: autohealing-app
          image: harshitrwt009/autohealing-app:latest  
          ports:
            - containerPort: 3001             # Your app listens on 3001

